// import type { Metadata } from "next";
import localFont from "next/font/local";
import Head from "next/head";
import "../styles/globals.css";
import type { AppProps } from 'next/app';
import "../styles/globals.css";
import { Wallet } from "./Wallet"

const geistSans = localFont({
    src: "../styles/fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "../styles/fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// export const metadata: Metadata = {
//     title: "Baby Swap",
//     description: "Generated by create next app",
// };

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Baby Swap</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Wallet>
                    <Component {...pageProps} />
                </Wallet>
            </div>
        </>
    );
}
